### ISSUE TITLE
Not listed in Package Control

### ISSUE THREAD

**Issue by grayghostvisuals** [saadq/Materialize#11]
Trying to install this on a diff. machine and currently Materialize does not show in pkg control on both machines.

**Comment by saadq** [comment]
That's weird, I haven't heard of anyone else having this issue.

![materialize](https://cloud.githubusercontent.com/assets/5678694/9411394/afa18b92-47f3-11e5-82a1-178cac1dd919.png)

Are you on Sublime Text 3 or Sublime Text 2? This theme requires you to be on ST3. Also, could you make sure you don't already have it installed? Open up the command palette with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and type in `Package Control: List Packages` and just make sure it isn't already listed there.

**Comment by grayghostvisuals** [comment]
Removed the package and it now shows up again in package control. Must have been a bad install on my part :\ Anyways thanks for the quick reply.

**Comment by saadq** [comment]
Np, glad it's working :)
