### ISSUE TITLE
Solarized Errors After Install

### ISSUE THREAD

**Issue by grayghostvisuals** [saadq/Materialize#12]
Got this error in the screenshot after a fresh installation of both ST3 and Materialize. Solarized is the only one that produces this error ATM:

![screenshot 2015-08-21 11 21 21](https://cloud.githubusercontent.com/assets/934322/9412003/69e0443c-47f7-11e5-9320-1cb1d1e19cf2.png)

**Comment by grayghostvisuals** [comment]
bah! I was mistyping. I'm off my game today it seems. Sorry for the troubles.

**Comment by saadq** [comment]
No worries, I'm tempted to make a Material Oceanic Seti theme now though.

**Comment by grayghostvisuals** [comment]
:+1:
