### ISSUE TITLE
The field "rename file" is not displayed.

### ISSUE THREAD

**Issue by thiagolucio** [saadq/Materialize#16]
the field "rename file" is not displayed.
When you click to rename a file, the input field where we enter the new name is not showing up, it's there but does not appear. I believe that lacks the choice of a contrasting color. Sorry mi english.

Look the img...
![sublimethemerenamenotshow](https://cloud.githubusercontent.com/assets/5756266/9467056/4016ad74-4b0f-11e5-8ded-50d0de17e6ef.jpg)

**Comment by saadq** [comment]
Please read the "Known Issues" at the bottom of the [README](https://github.com/saadq/Materialize#known-issues). The quick fix is to grab the border of the bottom box and move it around.

**Comment by thiagolucio** [comment]
Sorry about that...simple to solve..not a problem realy.

**Comment by saadq** [comment]
No worries, glad you were able to fix it.
