### ISSUE TITLE
vue icon is not getting displayed

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#19]
Hi, 
the original material theme displays the vue icon which is not getting displayed in the materialize theme 

please see the following links 
https://infinit.io/_/3evnXEf

https://infinit.io/_/gzhKFkX

**Comment by saadq** [comment]
I will have this fixed by tomorrow.

**Comment by saadq** [comment]
This issue should be fixed, I will push the changes to Package Control shortly. Please reopen the issue there is any further issue with it.

**Comment by saadq** [comment]
Changes have been made, please validate that the Vue icons are working when you get a chance.
