### ISSUE TITLE
Material Toy Chest Theme request

### ISSUE THREAD

**Issue by amucinom** [saadq/Materialize#20]
Hey saadq!! Your work is awesome, I'm loving all of the different themes that you have created!
I found a theme that used to be so popular but has since been forgotten, but it could make a comeback!
The name is Toy Chest, and here is the website: http://jacksongariety.github.io/toy-chest-theme/
Originally created by Jackson Gariety. It would be great if it could come alive!

Thank you for your great work again!

**Comment by saadq** [comment]
Thanks for the kind words! I'll have it done by today.

**Comment by amucinom** [comment]
No problem! And thank you!

**Comment by saadq** [comment]
I've made the theme, but I still have to update a lot of the documentation, screenshots, and messages before I push the changes to Package Control (I will probably be doing it tomorrow).

Here's a screenshot of what it will look like: http://i.imgur.com/j1t6ZYB.png

Please reopen this issue if there is something you'd like to change about the theme once its published on Package Control.

**Comment by amucinom** [comment]
No worries! Thank you so much for your hard work! I look forward to seeing it live and using the theme! Cheers!
