### ISSUE TITLE
Atom's One Dark

### ISSUE THREAD

**Issue by tillkruss** [saadq/Materialize#21]
I'd __love__ to see the [One Dark](https://atom.io/themes/one-dark-ui) theme from Atom ported to Sublime Text.

**Comment by saadq** [comment]
I don't really make the color schemes (the syntax highlighting), I only make the themes that match an existing color scheme. The "theme" is just the UI (stuff like the sidebar, quick panels, find, console, etc).

I found an existing color scheme for One Dark made by IceTimux: https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme

If possible, could you confirm that the colors are right and are what you're looking for? If they are, I can get to work on making the theme.

**Comment by tillkruss** [comment]
Amazing, thank you!
