### ISSUE TITLE
[Request] Could we install the themes from unique packages?

### ISSUE THREAD

**Issue by ZaLiTHkA** [saadq/Materialize#24]
As much as I appreciate the themes you've created, I must admit the rate of updates pushed to specific themes gets annoying quite quickly. So with that in mind.. :)

Would you consider publishing those theme branches with custom entries for Package Control? In this way, theme-specific package updates would only affect people with that theme, while core updates would still affect everyone as it currently does.

I'm not sure what your local dev environment looks like, but I would consider a of them to be themes with preset colour variations, so by lumping items like "Solarized" and "Spacegray" in there own packages, the general update distribution would be cut drastically, with theme-specific updates to `1/16` of what they currently are.

**Comment by saadq** [comment]
I apologize for my late response. I saw this very early on, but didn't respond. I definitely took what you said to heart, and have been thinking about a different way to structure this project so people wouldn't be annoyed by frequent updates. 

Unfortunately, for the short-term at least, putting the themes/color schemes as 20+ separate entries wouldn't be very practical right now. For right now, I have been in the middle of writing a blog post which will cover several topics (how to create a material theme with the color scheme you want, how to get rid of all the other assets/themes/schemes that you don't want to use), so hopefully these will be sufficient for right now.

**Comment by ZaLiTHkA** [comment]
No problem, thanks for the feedback. :)

With regards to my suggestion of using branches for the themes, one example of this is dbtek's [bootswatch-dist](https://github.com/dbtek/bootswatch-dist) repo. Either way, I'm very interested to see the blog post you mentioned, sounds like it will be quite useful.

**Comment by saadq** [comment]
That looks very interesting, thanks! I'm gonna check it out and maybe I can do this in a better way. The blog post will be done soon, but I also want to do an accompanying video for it that shows a step-by-step walkthrough, so hopefully I can have it out in ~ 1 week.
