### ISSUE TITLE
VimBlackboard Materialize Theme!!

### ISSUE THREAD

**Issue by Shadeslayer345** [saadq/Materialize#25]
I love this theme! It would be great if an adaptation of [VimBlackboard](https://packagecontrol.io/packages/Theme%20-%20Vim%20Blackboard) could be created!
![screenshot](https://cloud.githubusercontent.com/assets/5509676/10500542/e9edc738-72a6-11e5-90a9-336861d9a9b0.PNG)

**Comment by saadq** [comment]
I have finished with this theme, I will push the changes to Package Control within the next couple of days.

**Comment by Shadeslayer345** [comment]
Awesome! Thanks for all your hard work!

**Comment by saadq** [comment]
No problem. Here's a sneak-peek :)

<img width="1392" alt="screen shot 2015-11-15 at 7 52 34 pm" src="https://cloud.githubusercontent.com/assets/5678694/11172269/95dfb06c-8bd2-11e5-9043-4c7995e42462.png">

**Comment by jrappen** [comment]
@Shadeslayer345 issue should be closed by the next release

**Comment by jrappen** [comment]
https://github.com/saadq/Materialize/blob/master/Material%20Vim%20Blackboard.sublime-theme

**Comment by saadq** [comment]
I appreciate your patience. I've added the theme and pushed changes to Package Control. You should have this theme available in a couple of hours automatically. Please reopen this issue if you find any issues!
