### ISSUE TITLE
add karelvuong/st-primer

### ISSUE THREAD

**Issue by jrappen** [saadq/Materialize#28]
any chances of adding [karelvuong/st-primer](https://github.com/karelvuong/st-primer)?

**Comment by saadq** [comment]
There are a few versions of st-primer. Do you have any preferences or did you want me to do each one?

**Comment by jrappen** [comment]
I'm working with the light one, but whatever you are willing to do.

**Comment by saadq** [comment]
Hey jrappen, there are two version of the light themes in the link you sent. Is there a specific one you'd like me to do? I can do both of them like as well if you'd actually like to use both.

**Comment by jrappen** [comment]
I prefer the regular one.

**Comment by saadq** [comment]
I'll have it done and pushed to package control by tomorrow.

**Comment by jrappen** [comment]
any chance you're gonna push the updates to fix #28 and #25, which are apparently done? @saadq

**Comment by jrappen** [comment]
@saadq any updates on this issue?

**Comment by saadq** [comment]
Hey, @jrappen. Sorry for my late response, I've gotten a bit busy with work and finals. I will definitely push the changes for the two themes by the end of today, I actually needed to work on your request a bit more as the light themes require a bit more modification. I've also been working on a new optional feature called "sidebar-contrast" which lets you distinguish the color of the sidebar from the rest of your theme. Hopefully I can fit this into today's changes as well.

**Comment by saadq** [comment]
Update:

This hasn't been forgotten. The thing is, the original Material Theme went through a lot of updates and added a bunch of effects to the theme. I'm currently in the middle of implementing these changes (I basically have to recolor dozens of assets for the animations for each of the 20+ themes). I will be finished with finals by the 16, so I will have a lot of time to work on it. Thanks a lot for being so patient, I promise I'll have your theme to you soon!

Also, if you don't want to wait, I actually have your theme finished with all the newest updates. It hasn't been pushed to Package Control, but you can [e-mail](mailto:saad@saadquadri.com) and I could tell you how to use the theme right away.

**Comment by jrappen** [comment]
issue should be closed by the next release

**Comment by saadq** [comment]
Refer to [issue #30](https://github.com/saadq/Materialize/issues/30). The new release will be pushed by the end of this week. I appreciate the patience, I know this is long overdue.

**Comment by jrappen** [comment]
:+1:

**Comment by saadq** [comment]
I've added primer-light, and the contrast mode for all the themes as well. Package Control should update your theme within a couple of hours. Thanks so much for your patience! Please reopen this issue if you see any problems with the theme.
