### ISSUE TITLE
White Panels not working...

### ISSUE THREAD

**Issue by c0ppo** [saadq/Materialize#29]
I love monokai, but when using Monokai materialize theme, white panels plugin for material theme isn't working. Any chance you could fix that?

**Comment by saadq** [comment]
I've just created a new repository and pushed it to Package Control. It is going to be called **Materialize-White-Panels** and you'll be able to install it through Package Control within two hours. I appreciate your patience!

**Comment by saadq** [comment]
Sorry, scratch that – It might take longer than two hours. I sent the pull request to Package Control awhile ago, I just need to wait for them to put host my package.

**Comment by c0ppo** [comment]
Wohooo... Thanks for this :)

**Comment by saadq** [comment]
It just got pushed to Package Control, you should be to install it now!
