### ISSUE TITLE
Materialize does not support "theme_contrast_mode"

### ISSUE THREAD

**Issue by karbica** [saadq/Materialize#30]
When this option is enabled in user preferences, it has no effect on any of the Materialize themes. It'd be nice if this could also affect the extended themes from Materialize.

```javascript
"material_theme_contrast_mode": true
```
![screen shot 2016-01-04 at 5 27 58 pm](https://cloud.githubusercontent.com/assets/8563742/12105328/82f3fb54-b308-11e5-9b76-187c567e6f53.png)

```javascript
"material_theme_contrast_mode": false
```
![screen shot 2016-01-04 at 5 30 47 pm](https://cloud.githubusercontent.com/assets/8563742/12105360/eb5f8c80-b308-11e5-9420-b23b3250c4b0.png)

**Comment by saadq** [comment]
I'm working on a major release that will be pushed by the end of this week. The original creator of the Material theme added in some new effects, so I've been recoloring a bunch of animation frames for each theme. The new release will have those effects added in as well as `material_contrast_mode`.

**Comment by karbica** [comment]
I like the sound of that. Much appreciated!

**Comment by saadq** [comment]
I've just finished this feature, and I have pushed the changes to Package Control. Materialize should automatically update for you within a couple of hours (or you can just manually download the latest version if you want it right away). If you are unable to use the new feature, please reopen this issue. Thanks for your patience!
