### ISSUE TITLE
Indigo Accent

### ISSUE THREAD

**Issue by jackperry** [saadq/Materialize#31]
I'm not sure if this is a fork of Material-Theme (https://github.com/equinusocio/material-theme) or not, but if it is, could you add the new Indigo accent to this as well? It's my new favorite, really pops off the screen, but I'd like to continue using Material One Dark from this repo as well.

**Comment by saadq** [comment]
It is basically a fork of Material-Theme although I've deviated from it slightly. But this is a feature I can easily add, so I'll get on it as soon as I get home.

**Comment by jackperry** [comment]
Thanks a bunch!

**Comment by saadq** [comment]
Hey just giving you an update. It seems like he's made some changes to his theme and the new indigo folder icons look incompatible with Materialize. All the other indigo assets seem to work fine, so I'll still be able to do this for you, I'm just gonna need a bit more time to redo the folder icons. I should have it to you by tomorrow!

**Comment by jackperry** [comment]
Appreciate you going the extra mile.

**Comment by saadq** [comment]
Well, after spending a lot of time trying to redo the folder icons, I realized I'm pretty garbage at PhotoShop. Luckily, I was able to figure out how to make all the themes compatible with the new icon format, so I was able to modify them. 

I've just pushed the changes (better late than never :p), and Package Control should automatically update your theme within a couple of hours. Please reopen this issue if you find something wrong with it. 

Hope you like it :)

<img width="1392" alt="screen shot 2016-01-15 at 7 03 01 pm" src="https://cloud.githubusercontent.com/assets/5678694/12368639/46d823fa-bbbb-11e5-86a9-d46bd61be9be.png">

**Comment by jackperry** [comment]
Thanks man!
