### ISSUE TITLE
Renaming files isn't visible

### ISSUE THREAD

**Issue by MGHollander** [saadq/Materialize#32]
If I try to rename a file the field where the name is shown isn't visible. You can type but you don't see what you type.

**Comment by jrappen** [comment]
works for me with saadq/Materialize@09a5fd6

**Comment by saadq** [comment]
Please check the [**Known Issues**](https://github.com/saadq/Materialize#known-issues) info in the README. You basically just have to grab the border and pull the panel, and it should fix your problem. You can read more about the issue [here](https://github.com/equinusocio/material-theme/issues/67).

**Comment by MGHollander** [comment]
I'm sorry. Now I read your comment I remember... Thanks!
