### ISSUE TITLE
Sublime Text comment toggle command is broken in Gruntfile.js syntax

### ISSUE THREAD

**Issue by bmcminn** [saadq/Materialize#37]
Discovered the same problem in https://github.com/YabataDesign/afterglow-theme/issues/72 and @mknabe put together a solve for it that works and I have tested in this package as well. Will be filing a PR to solve this problem in Materialize.

**Comment by saadq** [comment]
Solved by this [PR](https://github.com/saadq/Materialize/pull/38). Thanks bmcminn!
