### ISSUE TITLE
Add hidpi support for Windows

### ISSUE THREAD

**Issue by vemacs** [saadq/Materialize#39]
With the Spacegray thing on ST3 (running on a Surface Pro 4 at 200% scaling), all of the assets are blurry. These include the arrows, tab close icon, tab overflow icon, and scrollbar:

![](http://i.imgur.com/9Iqa0ek.png)

Is it possible to introduce higher-res versions of these assets on Windows, or is this a ST3 bug?

**Comment by saadq** [comment]
Can you try restarting the editor? If that doesn't solve it, try reinstalling the theme and then restarting the editor right after that as well. Let me know how it goes.

**Comment by vemacs** [comment]
I added dpi_scale: 2.0 in my user preferences and restarted the editor to no avail. I also tried reinstalling the theme with Package Control and restarting the editor, which also didn't work.

**Comment by saadq** [comment]
Is this happening to you with the other themes in Materialize as well? Or is it a Spacegray specific thing?

**Comment by vemacs** [comment]
I tried Brogrammer and Solarized with the same results.

**Comment by saadq** [comment]
This is strange. The image you posted is usually what happens when the theme updates or when you haven't restarted the editor after installing it.

Does this problem occur when you use the original Material Theme?

**Comment by vemacs** [comment]
Sadly, yes (I installed it, applied it, and restarted the editor). Should I report this to them instead?

**Comment by saadq** [comment]
Sorry to hear that. Unfortunately, Materialize is basically nothing more than a fork of Material Theme with some minor modifications. equinusocio is the mastermind behind the creation of all of this, so he might be better suited to deal with this problem. So I would definitely recommend raising an issue there, and then if he is able to fix his themes, I can try to replicate his fix within Materialize.

**Comment by vemacs** [comment]
Okay. As a side note, I did run Ctrl+H on Material Spacegray.sublime-theme and replaced `.png` with` @2x.png`, and it did properly force the usage of hiDPI assets (with some missing ones on the scrollbar).

**Comment by saadq** [comment]
I can try out defaulting to the `2x` assets, once I get home, I'll keep you updated.

**Comment by vemacs** [comment]
Thanks! I've reported this to ST core: https://github.com/SublimeTextIssues/Core/issues/1073

The only potential issue I can see with forcing 2x assets is that margins are not respected on Windows (at least for the thumb_* images), so I have to downgrade to normal assets with those (not sure how the margins work) to get correct proportions. Not sure how that can be dealt with other than introducing additional margins.

**Comment by saadq** [comment]
Hi, just wanted to give you an update. I looked at the issue you made on the original Material theme. I really want to keep Materialize as closely aligned with the original Material theme as possible, so I'm going to hold off on making any changes until I see how he responds to it (I believe he has still left the issue open). Sorry about any inconvenience this may cause in the mean time!

**Comment by vemacs** [comment]
It's fine! I do have my temporary workaround, so it's not all lost
