### ISSUE TITLE
Strange sidebar highlighting

### ISSUE THREAD

**Issue by Solanar** [saadq/Materialize#40]
I'm using the Zenburn colour theme and noticed the following strange colouring issue on my side bar about two or three releases ago.

![materialize-zenburn-sidebar-bug](https://cloud.githubusercontent.com/assets/819536/12624335/babd2606-c4eb-11e5-8dc1-29b31c22a44b.PNG)

**Comment by saadq** [comment]
Very sorry about this! I seem to have messed up some of the settings when I fixing something else. I just sent a push to Package Control, your theme should be fixed automatically in a short while.

**Comment by saadq** [comment]
Should be fixed as of release [2.5.3](https://github.com/saadq/Materialize/releases/tag/2.5.3). Please reopen the issue if you still see anything wrong with the theme.

**Comment by Solanar** [comment]
Fixed! Thanks so much for fixing this, and so fast too. You should put up a donation link!
