### ISSUE TITLE
Add panel button from Build 3101

### ISSUE THREAD

**Issue by jrappen** [saadq/Materialize#41]
> Dev Build 3101 is out now at https://www.sublimetext.com/3dev
> There's now a button on the status bar to switch between panels. If you have a custom theme, the relevant class name is panel_button_control.
> Also changed is the way Sublime Text detects changes to open files. Sublime Text 2 would simply poll the current file whenever it was switched to. This has the disadvantage that any changes to the underlying file wouldn't be noticed until either the main window itself loses and then regains input focus, or the active file was changed to something else and then back. In practice, this was only an issue if there was a 3rd party changing the file behind the scenes. It also wouldn't notice background modifications to files that are never switched to.
> Sublime Text 3 by and large worked around the missed notification issue by subscribing to file system change notifications, so that it didn't need to poll. To work around file systems that don't publish change notifications, it still polls files when an application window goes from an unfocused to a focused state, but not when simply switching between files. 3101 will now poll the active file when the active file changes, to better handle file systems that don't send change notifications.

**Comment by jrappen** [comment]
see also equinusocio/material-theme#642

**Comment by saadq** [comment]
Yup, I saw that in the updates. I'd like to keep Materialize's themes consistent with Material Theme, so I'm going to wait and see if he's going to be adding a panel icon for his, and then I can follow suit. Otherwise, I can do it on my own.

**Comment by kurtextrem** [comment]
He's added them now.

**Comment by saadq** [comment]
Cool, I should have this done by today for all the themes.

**Comment by saadq** [comment]
Sorry about the delay on this, I was going to make it part of a bigger release and decided to delay it a bit since there was a default panel switcher icon added in. I've finished adding this feature in to all of the themes though and it should be released today.

**Comment by saadq** [comment]
This feature has been pushed to Package Control, your themes should update automatically. Please reopen if there are any issues!
