### ISSUE TITLE
Monokai Soda flavor

### ISSUE THREAD

**Issue by vassilmladenov** [saadq/Materialize#42]
I hope this isn't too similar to the Monokai theme, but I really like Soda theme's variant of Monokai with the darker background and brighter text. 

The scheme can be found in color-schemes.zip at
https://github.com/buymeasoda/soda-theme/blob/master/README.md

Would you consider adding Monokai Soda as a flavor of Materialize?

**Comment by saadq** [comment]
Not a problem

**Comment by saadq** [comment]
Material Monokai Soda has been added, your theme should update sometime soon automatically!

**Comment by vassilmladenov** [comment]
Sweet!! Can you do a write up of your workflow for generating a theme so we can follow your lead and submit PRs instead of forcing you to do each one?

**Comment by saadq** [comment]
Yup, I'm actually in the process of creating a "theme generator". You'll basically just have to put the name of the theme, and the color you want it to be and it will generate all the files/folders/assets for it. The only issue may be with some assets needing to be recolored, but I have a friend who may be able to help with automating that. Either way, the generator should be out soon with some detailed instructions.

**Comment by vassilmladenov** [comment]
Looking forward to it! Maybe we could hook it into ColorSublime and autogenerate for any CS theme. I have another question: the way themes are now, the modal dialogs are the exact same color as the text area and it's a little strange to not have them have some kind of border (i.e. the find and replace on Material Stereokai). Is there a flag for slightly more contrast or is it smarter to just mix and match a theme with a color scheme?

**Comment by saadq** [comment]
Ah, sorry there is a `material_theme_contrast_mode: true` option you can use in your preferences, but I think I forgot to set it for Monokai Soda or Augmented Reaction. I'll fix it in a bit!

**Comment by saadq** [comment]
Contrast Mode has been fixed for Monokai Soda as of release 2.5.5: https://github.com/saadq/Materialize/releases. **2.5.6** is the latest which has the fixed `.html.erb` language recognition.

It seems like there is currently a problem with Package Control's crawler, so once it is fixed your theme should be automatically updated. And of course, you can download the release manually for now and put it in your `Packages` folder if you'd like it right away.

Please reopen this issue if you still find any problems with the theme!
