### ISSUE TITLE
Is it possible to remove rounded corners on menus?

### ISSUE THREAD

**Issue by Sawtaytoes** [saadq/Materialize#43]
Is it possible to have no rounded corners on menus?

**Comment by saadq** [comment]
Materialize for the most part follows the same format as the original Material theme – all the customizable aspects of the theme are the same ones from their. I'd like to keep it consistent with Material Theme as much as possible, so it may be a better to put this issue on the original Material Theme repo. If equinusocio changes his theme to add this feature, I'd be happy to implement the changes for all of Materialize's themes as well! I'm going to close this for now, but please feel free to reopen if appropriate.

**Comment by Sawtaytoes** [comment]
Actually, I thought I posted in the original repo. Must've been in the wrong browser tab. I'll go post there now.
