### ISSUE TITLE
File icons missing version 2.5.8

### ISSUE THREAD

**Issue by saadq** [saadq/Materialize#45]
Materialize, like the original Material theme, uses Seti's file-type icons. It seems the newest dev build has caused issues with the icons, there is already an issue opened in Seti's theme [here](https://github.com/ctf0/Seti_ST3/issues/232).

There may be some other bugs as well with the tabs, so right now it's definitely a better idea to stick with build 3105 until Jon pushes a fix. He said it should be [fixed with the next build](https://forum.sublimetext.com/t/dev-build-3106/17982/9).

**Comment by saadq** [comment]
Fixed as of build 3107.

**Comment by dagomar** [comment]
After updating to 2.5.8 I am missing my file icons :'(

**Comment by saadq** [comment]
I apologize, this was my fault. I moved the themes out of the root directory into a separate folder in order to clean up the repo a bit, but that messed up some of the paths. I just pushed an update, and your theme should automatically update soon which should fix it. Sorry once again!

**Comment by dagomar** [comment]
Wow @saadq, thats very quick! No worries! Thank you for a wonderful theme :)

**Comment by saadq** [comment]
This should be fixed now, if your theme hasn't automatically updated yet you can open up the command palette with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and then type in `Package Control: Update Package` which should let you upgrade `Materialize`.

Please reopen this issue if there are still any problems.
