### ISSUE TITLE
Theme overriding the syntax association for .html.erb files

### ISSUE THREAD

**Issue by Trickierstinky** [saadq/Materialize#47]
It seems that this theme is suffering the same issue that the Material theme suffered whereby the theme is overriding the syntax association for `.html.erb` files and turning making the theme ignore the default syntax highlighting of `HTML(Rails)` and always force the syntax scheme to display as `HTML`.

Even if you set the `Open all with current extension as...` to be displayed as `HTML(Rails)` the next file you open falls back to `HTML`.

More information on the issue can be found https://forum.sublimetext.com/t/3103-html-erb-unable-to-change-default-syntax-highlighting/17335 . The link also shows a workaround for anyone experiencing the issue at the moment.

**Comment by saadq** [comment]
Hey @Trickierstinky, thanks for raising the issue! Sorry for not noticing this until now, I haven't done much Ruby. The [newest release](https://github.com/saadq/Materialize/releases/tag/2.5.6) has solved this issue. 

Package Control should be updating the theme automatically within a couple of hours, but it seems to be having some trouble detecting changes lately. I'm going to try to reach out to wbond about this problem, but for now you can download the release manually and put it into your `Packages` folder if you'd like it right away.

Please reopen the issue if you still find any problems with the `.html.erb` files!

**Comment by Trickierstinky** [comment]
Hey @saadq

I've manually installed the theme and it seems better, I still had to manually go in a select that `html.erb` files should be displayed as `HTML(Rails)` but after that it seems to have stuck, so I'm not sure if this is still a bug but either way, it now remembers the syntax.
