### ISSUE TITLE
Ctrl-k-2 not working after updates

### ISSUE THREAD

**Issue by openrisdev** [saadq/Materialize#48]
Several times on a row now I lose the Ctrl-k-2 function of sublime after there is an update to this theme. It becomes Ctrl-k-1. Really weird stuff, can't figure out how to fix this.

**Comment by saadq** [comment]
You're on Windows, correct? What is the <kbd>Ctrl</kbd>+<kbd>k</kbd>+<kbd>2</kbd> shortcut used for? Also, does restarting the editor fix the issue?

**Comment by openrisdev** [comment]
It is used for code folding at the second level - as in methods in a class
are.

Windows:
Edit->Code Folding->Fold level 2

**Comment by saadq** [comment]
There is usually graphical corruption when a theme updates and it may also be causing this issue, so it's usually always recommended to restart the editor when it happens anyways. Please reopen the issue if the hotkey doesn't work even after restarting the editor.
