### ISSUE TITLE
Colour Scheme problem with SublimeLinter

### ISSUE THREAD

**Issue by Sotiris-k** [saadq/Materialize#49]
If you have SublimeLinter installed then once you select the Materialize Monokai colour scheme for whatever reason in the user settings the colour scheme changes to:
`"color_scheme": "Packages/User/SublimeLinter/Material Monokai Soda (SL).tmTheme",`

**Comment by Sotiris-k** [comment]
Nevermind I found out it's the plugin's fault.

**Comment by saadq** [comment]
Yeah, it's basically does that in order to make the red outlines and such to display errors.
