### ISSUE TITLE
A little padding in the text control would be helpful

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#5]
I have often experienced that a little padding in the text control is very easy on the eyes. Might I ask you to please add that as well. 

For example , Material Theme comes with a default padding 

![image](https://cloud.githubusercontent.com/assets/473101/9094320/22a430da-3b7f-11e5-8001-6f2d32eb0d69.png)

While there is no padding in the Material Spacegray theme 
![image](https://cloud.githubusercontent.com/assets/473101/9094341/3d5016a6-3b7f-11e5-8c19-1e498825e098.png)

If i have not explained properly, my bad. Please note that the word index in the search control is padded a little bit in the Material theme while its not the case with the Material Spacegray theme.

**Comment by saadq** [comment]
Hmm, I'm pretty sure I didn't make any modifications to padding. This may have been a result from when I changed the colors of the overlays and tabs through Photoshop. Thanks for raising the issue, I'll try to find what may have caused this.

**Comment by saadq** [comment]
This should be fixed by tomorrow.

**Comment by saadq** [comment]
Sorry for the delay, there are some major additions being developed with the repo, and this will be fixed with those additions.

**Comment by saadq** [comment]
I apologize for the long wait. I've finished with the new themes, I've fixed the input bar on each of them to be like the one from the original Material themes. You can checkout the README for more details.

I'm currently waiting for my pull request to be merged for the repo's name-change, and then I'll be able to push my changes to Package Control.
