### ISSUE TITLE
Add template files

### ISSUE THREAD

**Issue by jrappen** [saadq/Materialize#50]
https://github.com/blog/2111-issue-and-pull-request-templates

---

also fix link at bottom of [README.md](https://github.com/saadq/Materialize/blob/master/README.md)

**Comment by saadq** [comment]
Thanks for informing me about this! Will do so soon

**Comment by saadq** [comment]
I've created an ISSUE_TEMPLATE.md and a CONTRIBUTING.md which you can find [here](https://github.com/saadq/Materialize/tree/master/.github). Going to hold off on a PULL_REQUEST_TEMPLATE.md for now. Thanks once again.
