### ISSUE TITLE
sidebar_tree row padding configurable

### ISSUE THREAD

**Issue by lordgiotto** [saadq/Materialize#53]
Hi, thanks for this theme, I really like it! :)
It would be great to have a configurable row_padding in sidebar_tree: for me is all too tight.

If you like I can make a pull request adding materialize_sidebar_small (default like now), materialize_sidebar_medium and materialize_sidebar_large to all themes.

Thank you!

Lorenzo

**Comment by saadq** [comment]
Hey @lordgiotto,

You're definitely right, the padding between the sidebar stuff is a bit too tight. I've noticed that in the original [Material Theme](), the padding is much more spaced out so I'm actually going to be pushing a change very soon that will make the padding the same as that. It will look more like this:

<img width="1392" alt="screen shot 2016-03-20 at 12 41 03 am" src="https://cloud.githubusercontent.com/assets/5678694/13902862/7635e0d2-ee34-11e5-96b1-21ba97063f7b.png">

I've been trying to keep the customization settings consistent with Material Theme, so I don't know if a setting for row_padding would be desirable right now, but it's definitely a possibility for the future. 

I'll have the padding spaced out by tomorrow.

**Comment by lordgiotto** [comment]
Thank you very much :)

**Comment by saadq** [comment]
I've pushed the changes, your theme will automatically update once Package Control recognizes the changes.

Please reopen the issue if there are any problems!

**Comment by gj1118** [comment]
Jeez-- The original material theme has support for compact sidebar via "material_theme_compact_sidebar" : true option. Can you please provide support for this ? Please note the sidebar is not usable for me because its a bit too much "space" padded. 

Thanks

**Comment by saadq** [comment]
`"material_theme_compact_sidebar" : true` was rather recent to Material Theme which is why I didn't know it existed, my apologies. As you can see from looking at issue [#54](https://github.com/saadq/Materialize/issues/54), I've added that feature.
