### ISSUE TITLE
Too much padding on the sidebar

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#54]
Creating a ticket because not sure if you would be reading #53 anymore (since you already marked it as resolved.If you happen to read #53 , please close this ticket

### Theme Issue:

1. OS:Windows/Mac
2. Sublime Text version: 3109
3. Materialize version: Latest
4. Description of issue:
The original material theme has support for compact sidebar via 
```"material_theme_compact_sidebar" : true```
option. Can you please provide support for this ? Please note the sidebar is not usable for me because its a bit too much "space" padded.

5. Screenshot of issue (if appropriate):
![image](https://cloud.githubusercontent.com/assets/473101/13909971/8f5f7df8-eef1-11e5-9c97-9f2a2a679249.png)

Thanks and Regards
Gagan

**Comment by saadq** [comment]
I was not aware that Material Theme had a `"material_theme_compact_sidebar" : true` feature. Working on this right now.

**Comment by gj1118** [comment]
Thanks..

**Comment by saadq** [comment]
This feature has been added, your themes should update shortly. Please reopen the issue if there are any problems with the new `material_theme_compact_sidebar` feature.
