### ISSUE TITLE
Illegible colors for light themes

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#55]
### Theme Issue:

1. OS: Windows/Mac
2. Sublime Text version: 3109
3. Materialize version: Latest
4. Description of issue:
I am using the Material Solaried Light theme . I have noticed that the tab fore color and the selected file forecolor in the sidebar is white, which makes it ineligible to read the headings. 
5. Steps to reproduce (if appropriate):

- Change theme to Material Solarized Light
- Open a few files in few tabs
- Notice the color of the current file in the tab bar as well as the sidebar.

6. Screenshot of issue (if appropriate):
![image](https://cloud.githubusercontent.com/assets/473101/13920406/324ae654-ef49-11e5-80ca-a44045db123a.png)

**Comment by saadq** [comment]
This is an issue that I'll have to fix for the older light themes (Solarized Light and Spacegray Light) as I didn't know much about theme customization back then. I believe Material Primer Light should be fine as I did that one pretty recently.

**Comment by gj1118** [comment]
Yep, I just checked with the primer light and it does work well out of the box - Thanks for the information.

**Comment by saadq** [comment]
How do these look?

### Solarized Light
<img width="1392" alt="screen shot 2016-03-21 at 10 08 14 am" src="https://cloud.githubusercontent.com/assets/5678694/13921166/f396b5c4-ef4c-11e5-807c-0c34a75801ca.png">

### Spacegray Light
<img width="1392" alt="screen shot 2016-03-21 at 10 08 55 am" src="https://cloud.githubusercontent.com/assets/5678694/13921176/fd0c1ffe-ef4c-11e5-9c49-96b274425668.png">

**Comment by gj1118** [comment]
I am liking what I am seeing. However , can you please add a bit more
contrast to the tabs which are not the current tab (for example - index.js
from your snapshots) ?. It would make for easier reading.

Thanks and Regards
Gagan

---------------------------
With Regards
Gagan Janjua

**Comment by saadq** [comment]
What exactly do you mean by contrast? Are you asking to make the names less visible for the tabs that aren't the current one?

**Comment by gj1118** [comment]
I was suggesting otherwise. I was asking if the names could be made more readable for the tabs that aren't the current one. Sorry for the confusion - that was my bad. 

Thanks and Regards
Gagan

**Comment by saadq** [comment]
I've darkened the fonts for the unselected tabs, your themes should be updating shortly.

**Comment by gj1118** [comment]
Thanks
