### ISSUE TITLE
option for setting the width of the grid separator

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#56]
### Theme Issue:

1. **OS**: Windows/Mac

2. **Sublime Text version**:3109

3. **Materialize version**: Latest

4. **Description of issue**:
Can you please add an option for users (like me ) to disable the grid separator . It stands out like a sore thumb whenever I am working with multiple groups . Having an option, to turn that grid line on or off, would sit well with everybody (people who like it and people who don't like it) . 

5. **Steps to reproduce (if appropriate)**:
Open multiple files in multiple groups.

6. **Screenshot of issue (if appropriate)**:

![image](https://cloud.githubusercontent.com/assets/473101/14055876/d9e75b3e-f2bb-11e5-8c57-e98c1819901f.png)

**Comment by saadq** [comment]
This isn't really a width issue, it's more of a color issue. I'm going to have to go through each theme and choose a more appropriate color for the grid border to make sure it doesn't end up sticking out like that.

**Comment by gj1118** [comment]
I have a theme override as follows. 

```
  /* @ GRID LAYOUT
   * Grid style
  ========================================================================= */

    {
      "class": "grid_layout_control",
      "border_size": 0,
      "border_color": [34, 45, 51]
    },
```

Note that I have set the border_size to 0. 

Thanks and Regards
Gagan

**Comment by saadq** [comment]
Yeah, setting it to 0 would remove the border completely. Do you not like it at all? Even if it were a better color like here?

<img width="1392" alt="screen shot 2016-03-28 at 10 18 38 am" src="https://cloud.githubusercontent.com/assets/5678694/14079817/8ff25456-f4ce-11e5-8bb0-fee4d04a1831.png">

**Comment by gj1118** [comment]
Can we have both of them ?  I must admit the color looks nice but an option to not have it at all would also do me a world of good. 

I apologize for being greedy.

Thanks and Regards
Gagan

**Comment by saadq** [comment]
Sorry about the long wait, I've gotten kinda busy with work and school especially since it's almost time for finals. I'll have this feature implemented by tomorrow or the day after.

**Comment by saadq** [comment]
I've changed the grid color for each theme to be more appropriate, please let me know if there are any issues. And once again, feel free to reach out to the original creator of the Material Theme if you would want a feature to disable the grid border.
