### ISSUE TITLE
New Theme request : Theme Numix Light /Dark

### ISSUE THREAD

**Issue by gj1118** [saadq/Materialize#58]
Can you please port the light and dark versions of Theme numix

### Theme Request:

1. Theme Name: Theme Numix Light
2. Link to the color scheme: https://packagecontrol.io/packages/Theme%20-%20Numix%20Light

1. Theme Name :  Theme Numix 
2. Link to the color scheme : https://packagecontrol.io/packages/Theme%20-%20Numix

Thanks and Regards
Gagan

**Comment by saadq** [comment]
Hey @gj1118, it looks like these are **themes**, not **color schemes**. Materialize is basically just me making "Material" themes based on color schemes. If you still want Materialized themes based on the links you showed me, I would definitely suggest asking the owner of those packages what color schemes they are using. Feel free to reopen this issue if you get that information.
