### ISSUE TITLE
Folder & Tab colors wrong for - Spacegray Eighties Theme

### ISSUE THREAD

**Issue by mrlami** [saadq/Materialize#60]
- OS: Mac
- Sublime Text version: 3
- Materialize version: latest
- Description of issue: Folder & Tab colors wrong for - Spacegray Eighties Theme
- Steps to reproduce: Use below settings in preferences

```
    "material_theme_compact_sidebar": true,
    "material_theme_small_statusbar": true,
    "material_theme_small_tab": true,
    "material_theme_compact_panel": true,
    "material_theme_contrast_mode": true,
    "color_scheme": "Packages/Materialize/schemes/Material Spacegray Eighties.tmTheme",
    "theme": "Material Spacegray Eighties.sublime-theme",
```

- Screenshot(s) attached!

![image](https://cloud.githubusercontent.com/assets/1946090/14908093/2113c64c-0da0-11e6-9b3a-369463986fbd.png)

**Comment by saadq** [comment]
Hey @mrlami, thanks for filling out all the details thoroughly. What exactly do you mean by wrong colors? It doesn't seem like you have any accent setting enabled so that's the default one.

**Comment by mrlami** [comment]
@saadq I assumed it would be a different (lighter) color for Spacegray Eighties theme (different form just Spacegray).

Is there a simple way to change the folder icons/color?

**Comment by saadq** [comment]
Is there a certain color you were hoping for? Unfortunately, the tabs and folder icons are assets that you would have to recolor in something like Photoshop. The simplest way to change them would be to use one of the predefined accent colors, but if you wanted to use a different color you would have to recolor the assets for the theme.

Here are the available accent colors that you can use by putting one of these in your Preferences:

```
    "material_theme_accent_lime": true,
    "material_theme_accent_purple": true,
    "material_theme_accent_red": true,
    "material_theme_accent_orange": true,
    "material_theme_accent_yellow": true,
    "material_theme_accent_indigo": true
```

For example, if you did

```
"material_theme_accent_indigo": true
```

your theme would look like this:

<img width="1392" alt="screen shot 2016-04-29 at 6 28 17 pm" src="https://cloud.githubusercontent.com/assets/5678694/14931286/2de50b9a-0e38-11e6-9d6f-175668b13bd7.png">
