### ISSUE TITLE
Error on Syntax Highlighting for HTML attributes

### ISSUE THREAD

**Issue by KaduAmaral** [saadq/Materialize#65]
### Theme Issue: Material Theme (default) Color Scheme

OS: **Windows 10 (64x)**
Sublime Text version: **Sublime Text 3 (64x)**
Materialize version: **last update**
Description of issue: **Error on Syntax Highlighting for HTML attributes, when put a PHP tag into a HTML tag.**

Steps to reproduce: **Put a PHP tag into HTML tag:**

```php
<a href="<?=$somelink?>" class="btn btn-link">Some Link</a>
```

Screenshot of issue:

![erro-syntax-hl](https://cloud.githubusercontent.com/assets/4316607/15473448/7f2d0cb8-20d6-11e6-9a94-8fe6ba2232de.png)

**Comment by saadq** [comment]
Hey there @KaduAmaral, it looks like you're using a color scheme from [Material Theme](http://github.com/equinusocio/material-theme), not Materialize. You'll probably want to open this issue over there.

**Comment by KaduAmaral** [comment]
OMG, it's true, sorry... :confounded:

**Comment by KaduAmaral** [comment]
I've tried use Materialize instead of Material Theme, and happens the same bug.

**Comment by saadq** [comment]
Thanks for letting me know. Which color schemes cause this issue? And can you paste the code you've been trying out so I can also use it?

**Comment by KaduAmaral** [comment]
I removed all themes and restart sublime text some times and after I install the themes again the problem was solved. Thanks.
