### ISSUE TITLE
Error on Syntax Highlighting on Javascript with PHP Block

### ISSUE THREAD

**Issue by KaduAmaral** [saadq/Materialize#66]
Javascript without syntax highlighting when between PHP condition:

![erro-js-syntax-hl](https://cloud.githubusercontent.com/assets/4316607/15478691/3d91c926-20f2-11e6-8f75-dafaba39270f.png)

**Comment by saadq** [comment]
Closing this, for the same reason as [#65](https://github.com/saadq/Materialize/issues/65).

**Comment by KaduAmaral** [comment]
I've tried use Materialize instead of Material Theme, and happens the same bug.

**Comment by KaduAmaral** [comment]
I think this is a Sublime problem and not Theme, look, without any theme this happens too:

![erro-syntax-js-sem-tema](https://cloud.githubusercontent.com/assets/4316607/15539118/ee39c62e-2256-11e6-86d5-7c7493d29919.png)
