### ISSUE TITLE
feature request - Folders

### ISSUE THREAD

**Issue by ginfuru** [saadq/Materialize#68]
In the sidebar, could there be an option for folders to use the default arrows in place of the folder icon?

If this is already a feature, just let me know what I'm missing.

**Comment by saadq** [comment]
Hey @ginfuru, feature requests for any of the themes should be done over at the original [Material Theme](github.com/equinusocio/material-theme). I'm trying to keep Materialize consistent with the original one, so if the change you request is implemented there I would be happy to implement them with Materialize. The creator of Material Theme is very responsive and you'll definitely get your issue looked at over there. I'll close this for now, but feel free to reopen it if it gets accepted into Material Theme.
