### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by paradox41** [saadq/Materialize#7]
OSX 10.10.4, ST3

Using the Material Monokai theme + Material Monokai color scheme, when I hover over the line numbers, this is what I see:

![screen shot 2015-08-17 at 8 31 47 am](https://cloud.githubusercontent.com/assets/2791730/9304866/a460c946-44ba-11e5-9635-9ce628fa7012.png)

It might be a missing code folding icon, but only one that appears on hover. The green down arrow appears for me when I hover __over__ the missing asset itself. Hopefully that helps. Let me know if there is anything else I can provide.

Nice themes as well btw!

**Comment by saadq** [comment]
Hi paradox41,

Thanks for raising the issue. This is a bit strange as I can't really replicate the issue:

When I hover over the line numbers: 
<img width="1392" alt="screen shot 2015-08-17 at 8 49 22 am" src="https://cloud.githubusercontent.com/assets/5678694/9305172/0034b3ac-44bd-11e5-8738-4a59c0edb652.png">

and when I hover over the arrow:
<img width="1392" alt="screen shot 2015-08-17 at 8 49 30 am" src="https://cloud.githubusercontent.com/assets/5678694/9305180/0ae1f9cc-44bd-11e5-9f25-e7857ff6a3cb.png">

I made some folder changes yesterday that may not have automatically updated for you. Can you try uninstalling the package and reinstalling it? Let me know what happens.

**Comment by paradox41** [comment]
Interesting. I reinstalled (restarted sublime text after uninstalling) and I still have the same issue. 

Do you use SublimeLinter by any chance? I wonder if the path to the color scheme has anything to do. Although, FWIW, I've used other themes without the same issue, but maybe this is a start. Here is the path that gets set whenever I change the color scheme: `"Packages/User/SublimeLinter/Material Monokai (SL).tmTheme"`

**Comment by saadq** [comment]
<img width="1392" alt="screen shot 2015-08-17 at 9 23 28 am" src="https://cloud.githubusercontent.com/assets/5678694/9305732/ab2dba70-44c1-11e5-9fff-a598ad4ad8be.png">

It seems to be working fine for me with SublimeLinter. My color scheme uses the same path as yours, but this seems to be a theme related issue, not a color scheme one.

What's more is that the specific asset you are having an issue with is a common one, not a monokai-specific one. Could you send me a screenshot of your entire editor? Also, could you do <kbd>⌘</kbd> + <kbd>F</kbd> and just check if any of the assets are missing from the bottom bar, or from anywhere else in the editor such as file type icons, etc?

**Comment by paradox41** [comment]
Yup. It doesn't look like there are any assets missing
![screen shot 2015-08-17 at 9 50 11 am](https://cloud.githubusercontent.com/assets/2791730/9306310/76c80548-44c5-11e5-8dd4-8d4d596730fd.png)

**Comment by JulianNorton** [comment]
Confirming this issue.

![screen shot 2015-08-17 at 10 04 31 am](https://cloud.githubusercontent.com/assets/2412992/9306606/69f3131a-44c7-11e5-9273-902e662e1e82.png)

Here are my user settings:
`
{
	"always_show_minimap_viewport": true,
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": ".",
			"selector": "source.js"
		}
	],
	"bold_folder_labels": true,
	"color_scheme": "Packages/User/SublimeLinter/Brogrammer (SL).tmTheme",
	"font_face": "Input Mono Narrow",
	"font_size": 14,
	"ignored_packages":
	[
		"All Autocomplete",
		"AngularJS",
		"Djaneiro",
		"Material Theme",
		"Vintage"
	],
	"indent_guide_options":
	[
	],
	"line_numbers": true,
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"material_spacegray_small_statusbar": true,
	"material_spacegray_small_tab": true,
	"material_theme_accent_purple": true,
	"mid_line_tabs": true,
	"overlay_scroll_bars": "enabled",
	"tab_size": 2,
	"theme": "Material Oceanic Next.sublime-theme",
	"translate_tabs_to_spaces": true,
	"word_wrap": true
}
`

**Comment by saadq** [comment]
Thanks @JulianNorton. It seems the issue is coming from `"material_theme_accent_purple": true,`. Removing that option seems to fix the asset issue. I'll take a look at the code and try to fix the problem.

**Comment by paradox41** [comment]
Yup. Forget to mention I use a different accent color. 

Thank you for your prompt response!

**Comment by saadq** [comment]
This issue has now been resolved. I've pushed the changes to Package Control which can take about an hour to update. Thanks for bringing this to my attention. 

<img width="1392" alt="screen shot 2015-08-17 at 10 57 49 am" src="https://cloud.githubusercontent.com/assets/5678694/9307854/d4f895ca-44ce-11e5-8621-a7af2b0c9624.png">

**Comment by paradox41** [comment]
Thanks for fixing it so quickly! Will let you know when it hits

**Comment by JulianNorton** [comment]
I just did `package control: upgrade package` for update. and the issue has now been resolved.

**Comment by saadq** [comment]
The latest version is on Package Control, but for some reason it is not auto-updating. I'm not sure why that it is but, like @JulianNorton said, you can just do `Package Control: Upgrade Package` or just reinstall the theme and it should work fine.

**Comment by paradox41** [comment]
Confirmed. It works. Thanks again.
