### ISSUE TITLE
Sidebar is blank

### ISSUE THREAD

**Issue by User7716** [saadq/Materialize#74]
1. OS:win 8.1 pro
2. Sublime Text version:2
3. Materialize version: Spacegray
4. Description of issue: Even after restart several times, the sidebar issue isn't fixed
    The theme works very well, but the sidebar has turned black, and i can't see the list of files in the opened folder in the left as shown in the screenshot
5. Steps to reproduce (if appropriate):
6. Screenshot of issue (if appropriate):
![screenshot 345](https://cloud.githubusercontent.com/assets/20397416/16755289/e3709cb2-47af-11e6-91e5-d85bfd850ab3.png)

**Comment by saadq** [comment]
I'm fairly certain that you need to be using Sublime Text 3 for Material Theme or Materialize to work properly. I would highly recommend using ST3 over ST2, it has several improvements and is faster. Even though it is technically in "beta", it is just as stable (if not more) than ST2.
