### ISSUE TITLE
Removing theme breaks folder view and I feel utterly mizerable now :(

### ISSUE THREAD

**Issue by zladuric** [saadq/Materialize#75]
### Theme Issue:

1. OS: Ubuntu 14.04 64bit
2. Sublime Text version: 3, build 3114
3. Materialize version: latest from package control
4. Description of issue: Removing theme broke my folder/files view.

Tried installing a different theme and fdidling with color themes, but the folders view remained broken.. The only thing I suspect will work is resetting sublime completely.

Then I tried reinstalling the theme, that fixed the problem. Then I've removed the theme again and got the problem back.

5. Steps to reproduce (if appropriate):

Install theme.
Remove theme.

6. Screenshot of issue (if appropriate):

This is the screenshot before restarting. After restarting the folder view is simply black box.

But if you hide/show the folder view (Ctrl-K twice), you get the partial view again.

![image](https://cloud.githubusercontent.com/assets/1014367/16914472/6408a710-4cf2-11e6-885f-664381d901dd.png)

I'll probably just kill the config folder completely and reinstall my plugins, but will keep my config folder if needed for further investigation.

**Comment by saadq** [comment]
When you removed the theme, did you make sure to update your `theme` setting in your Preferences file? If you still have the theme applied when it doesn't exist anymore, that most likely will be the cause of your issue. Also, make sure to try restarting your editor. Let me know if there are still issues, but I don't see how this could be a Materialize bug.

**Comment by zladuric** [comment]
Possibly, didn'tt check that. Lemme fire up the old config folder...yep, that was it!

Thanks and sorry for raising a false alarm. I've wanted to also say that this _may not be an issue_, but I forgot that part :)

Thanks again, anyway.

**Comment by saadq** [comment]
No problem, glad you got it fixed. And sorry to see you go D: haha.
