### ISSUE TITLE
No icon for LICENSE or .gitignore

### ISSUE THREAD

**Issue by sotojuan** [saadq/Materialize#8]
Just a minor issue—icons for LICENSE and .gitignore files aren't showing up:

![](http://i.imgur.com/NDXIZuJ.png)

**Comment by saadq** [comment]
That's strange. I don't think there was ever an icon for .gitignore in the original Material theme, but I'm not sure why your LICENSE icon isn't showing up. It seems to work fine for me: 

<img width="1392" alt="screen shot 2015-08-17 at 6 16 59 pm" src="https://cloud.githubusercontent.com/assets/5678694/9317847/4356a6be-450c-11e5-926f-bfa0a9b2131f.png">

Could you try uninstalling the theme and then reinstalling it and see if that fixes it?

**Comment by saadq** [comment]
I've added a "Langs" folder to the theme (which is what Seti uses for their file-type icons). This might be able to fix your issue with the file type icons. Package Control will update within an hour and hopefully your problem gets fixed. I'll leave the issue open until you can verify.

<img width="108" alt="file" src="https://cloud.githubusercontent.com/assets/5678694/9318628/450ca484-4513-11e5-8cac-f5d1495cc417.png">

**Comment by saadq** [comment]
The fix was verified.
